import * as THREE from 'three';
import {clampEnemy01,type EnemyMotionProfile,type EnemyPose,type EnemyHitPose,type EnemyDefeatPose} from './shared';
export type CritterBehaviorId='critter-roll'|'critter-acorn';
const idle=(now:number,phase=0):EnemyPose=>{const s=Math.sin(now*2.1+phase),t=Math.sin(now*1.45+phase*.7);return{scaleX:1+s*.012,scaleY:1-s*.01,scaleZ:1+s*.01,jump:0,wobbleZ:s*.012,travel:0,releaseProgress:-1,secondary:{headNod:s*.025,wag:t*.07,earDrop:Math.max(0,-s)*.025}}};
const move=(now:number,phase=0):EnemyPose=>{const c=(now*2.05+phase)%1,j=Math.abs(Math.sin(c*Math.PI))* .045;return{scaleX:1-j*.09,scaleY:1+j*.12,scaleZ:1-j*.035,jump:j,wobbleZ:Math.sin(c*Math.PI*2)*.025,travel:0,releaseProgress:-1,secondary:{headNod:-j*.35,wag:Math.sin(c*Math.PI*2)*.16,earDrop:j*.20}}};
const hit=(u:number,side:number):EnemyHitPose=>{const p=Math.sin(clampEnemy01(u)*Math.PI);return{scaleX:1+p*.07,scaleY:1-p*.12,scaleZ:1+p*.04,rotationZ:side*p*.08,secondary:{shellCurl:p*.22,wag:-side*p*.18,earDrop:p*.18}}};
const defeat=(u:number,side:number):EnemyDefeatPose=>{const t=clampEnemy01(u),c=Math.sin(Math.min(1,t/.72)*Math.PI/2),f=clampEnemy01((t-.88)/.12);return{scaleX:1+c*.15,scaleY:1-c*.34,scaleZ:1+c*.06,rotationZ:side*c*.62,yOffset:-.018*c,lateralDrift:side*.12*c,backwardDrift:.07*c,opacity:1-f,secondary:{shellCurl:c*.24,wag:side*.85*c,earDrop:.35*c,headNod:side*.32*c}}};
export function rollAttack(u:number):EnemyPose{const t=clampEnemy01(u),curl=t<.30?Math.sin(t/.30*Math.PI/2):t<.68?1:1-clampEnemy01((t-.68)/.32),roll=t>=.30&&t<.68?Math.sin((t-.30)/.38*Math.PI):0;return{scaleX:1+curl*.08,scaleY:1-curl*.14,scaleZ:1+curl*.07,jump:roll*.045,wobbleZ:roll*.30,travel:roll,releaseProgress:t>=.30?(t-.30)/.70:-1,secondary:{shellCurl:curl*.28,headNod:curl*.28,earDrop:curl*.24}}}
export function acornAttack(u:number):EnemyPose{const t=clampEnemy01(u),ant=t<.34?Math.sin(t/.34*Math.PI/2):0,recoil=t>=.46?Math.sin(clampEnemy01((t-.46)/.28)*Math.PI):0;return{scaleX:1+ant*.05,scaleY:1-ant*.10-recoil*.04,scaleZ:1+ant*.03,jump:recoil*.025,wobbleZ:0,travel:-recoil*.05,releaseProgress:t>=.46?(t-.46)/.54:-1,secondary:{wag:-ant*.55+recoil*.65,earDrop:ant*.10,headNod:-ant*.10+recoil*.08}}}
function acornMesh(){const g=new THREE.Group();g.name='AcornProjectile';const nut=new THREE.Mesh(new THREE.SphereGeometry(.045,12,9),new THREE.MeshStandardMaterial({color:'#9a6338',roughness:.8}));nut.scale.set(.9,.8,1.15);g.add(nut);const cap=new THREE.Mesh(new THREE.SphereGeometry(.035,10,7),new THREE.MeshStandardMaterial({color:'#6f482e',roughness:.9}));cap.scale.set(1,.6,.6);cap.position.z=.045;g.add(cap);return g}
const profiles:Record<CritterBehaviorId,EnemyMotionProfile>={
 'critter-roll':{familyId:'critter',idle,move,attack:rollAttack,hit,defeat,moveDuration:1.18,moveDistance:.76,attackDuration:.74,attackTravelDistance:.38,contactU:.67,defeatDuration:1.0},
 'critter-acorn':{familyId:'critter',idle,move,attack:acornAttack,hit,defeat,moveDuration:1.08,moveDistance:.90,attackDuration:.76,attackTravelDistance:.06,contactU:.46,defeatDuration:1.0,projectile:{kind:'acorn',flightSeconds:.46,createMesh:acornMesh,arcHeight:(u)=>Math.sin(clampEnemy01(u)*Math.PI)*.18}}
};
export const getCritterMotionProfile=(id:CritterBehaviorId)=>profiles[id];
