import * as THREE from 'three';
import {clampEnemy01,type EnemyMotionProfile,type EnemyPose,type EnemyHitPose,type EnemyDefeatPose} from './shared';
export type FlowerBehaviorId='flower-bud-poke'|'flower-pollen';
const idle=(now:number,phase=0):EnemyPose=>{const s=Math.sin(now*2.0+phase),b=Math.sin(now*3.1+phase*.5);return{scaleX:1+s*.01,scaleY:1-s*.008,scaleZ:1+s*.012,jump:Math.max(0,b)*.006,wobbleZ:s*.016,travel:0,releaseProgress:-1,secondary:{headNod:s*.045,open:b*.025,primaryBend:s*.025}}};
const move=(now:number,phase=0):EnemyPose=>{const c=(now*1.75+phase)%1,j=Math.abs(Math.sin(c*Math.PI))* .055;return{scaleX:1-j*.10,scaleY:1+j*.16,scaleZ:1-j*.04,jump:j,wobbleZ:Math.sin(c*Math.PI*2)*.025,travel:0,releaseProgress:-1,secondary:{headNod:-j*.65,primaryBend:j*.25}}};
const hit=(u:number,side:number):EnemyHitPose=>{const p=Math.sin(clampEnemy01(u)*Math.PI);return{scaleX:1+p*.05,scaleY:1-p*.10,scaleZ:1+p*.03,rotationZ:side*p*.08,secondary:{headNod:-p*.34,open:-p*.12,primaryBend:side*p*.12}}};
const defeat=(u:number,side:number):EnemyDefeatPose=>{const t=clampEnemy01(u),c=Math.sin(Math.min(1,t/.72)*Math.PI/2),f=clampEnemy01((t-.88)/.12);return{scaleX:1+c*.12,scaleY:1-c*.36,scaleZ:1+c*.04,rotationZ:side*c*.48,yOffset:-.02*c,lateralDrift:side*.09*c,backwardDrift:.06*c,opacity:1-f,secondary:{headNod:side*.85*c,open:.18*c,primaryBend:side*.34*c}}};
export function budPoke(u:number):EnemyPose{const t=clampEnemy01(u),ant=t<.32?Math.sin(t/.32*Math.PI/2):0,rel=t>=.32&&t<.62?Math.sin((t-.32)/.30*Math.PI/2):t>=.62?1-clampEnemy01((t-.62)/.38):0;return{scaleX:1+ant*.05,scaleY:1-ant*.12,scaleZ:1+ant*.03,jump:Math.sin(t*Math.PI)*.045,wobbleZ:0,travel:rel,releaseProgress:t>=.32?(t-.32)/.68:-1,secondary:{headNod:-ant*.36+rel*.58,open:-ant*.25+rel*.18,primaryBend:-ant*.16}}}
export function pollenAttack(u:number):EnemyPose{const t=clampEnemy01(u),inflate=t<.40?Math.sin(t/.40*Math.PI/2):t<.52?1:1-clampEnemy01((t-.52)/.30),recoil=t>=.50?Math.sin(clampEnemy01((t-.50)/.28)*Math.PI):0;return{scaleX:1+inflate*.07,scaleY:1+inflate*.08-recoil*.05,scaleZ:1+inflate*.07,jump:recoil*.02,wobbleZ:Math.sin(t*Math.PI*2)*.018,travel:-recoil*.06,releaseProgress:t>=.50?(t-.50)/.50:-1,secondary:{open:inflate*.28,headNod:recoil*.10}}}
function pollenMesh(){const g=new THREE.Group();g.name='FlowerPollenProjectile';const core=new THREE.Mesh(new THREE.SphereGeometry(.038,10,8),new THREE.MeshBasicMaterial({color:'#ffe6a4',transparent:true,opacity:.86,depthWrite:false}));g.add(core);for(let i=0;i<4;i++){const a=i/4*Math.PI*2,m=new THREE.Mesh(new THREE.SphereGeometry(.010,8,6),new THREE.MeshBasicMaterial({color:'#fff4c7',transparent:true,opacity:.72,depthWrite:false}));m.position.set(Math.cos(a)*.052,Math.sin(a)*.028,Math.sin(a)*.018);g.add(m)}return g}
const profiles:Record<FlowerBehaviorId,EnemyMotionProfile>={
 'flower-bud-poke':{familyId:'flower',idle,move,attack:budPoke,hit,defeat,moveDuration:1.45,moveDistance:.68,attackDuration:.66,attackTravelDistance:.34,contactU:.60,defeatDuration:1.0},
 'flower-pollen':{familyId:'flower',idle,move,attack:pollenAttack,hit,defeat,moveDuration:1.5,moveDistance:.64,attackDuration:.80,attackTravelDistance:.08,contactU:.50,defeatDuration:1.0,projectile:{kind:'pollen',flightSeconds:.45,createMesh:pollenMesh,arcHeight:(u)=>Math.sin(clampEnemy01(u)*Math.PI)*.14}}
};
export const getFlowerMotionProfile=(id:FlowerBehaviorId)=>profiles[id];
