import * as THREE from 'three';
import { clampEnemy01, type EnemyMotionProfile, type EnemyPose, type EnemyHitPose, type EnemyDefeatPose } from './shared';
export type LeafBehaviorId='leaf-hop-slap'|'leaf-whirl';
const hit=(u:number,side:number):EnemyHitPose=>{const p=Math.sin(clampEnemy01(u)*Math.PI);return{scaleX:1+p*.05,scaleY:1-p*.11,scaleZ:1+p*.03,rotationZ:side*p*.11,secondary:{primaryBend:side*p*.28,secondaryBend:-side*p*.18}}};
const defeat=(u:number,side:number):EnemyDefeatPose=>{const t=clampEnemy01(u),c=Math.sin(Math.min(1,t/.7)*Math.PI/2),f=clampEnemy01((t-.86)/.14);return{scaleX:1+c*.15,scaleY:1-c*.40,scaleZ:1+c*.05,rotationZ:side*c*.42,yOffset:-.025*c,lateralDrift:side*.11*c,backwardDrift:.08*c,opacity:1-f,secondary:{primaryBend:side*.75*c,secondaryBend:-side*.45*c}}};
export function leafIdle(now:number,phase=0):EnemyPose{const s=Math.sin(now*2.2+phase);return{scaleX:1+s*.012,scaleY:1-s*.008,scaleZ:1+s*.01,jump:Math.max(0,Math.sin(now*2+phase))*.008,wobbleZ:s*.022,travel:0,releaseProgress:-1,secondary:{primaryBend:s*.08,secondaryBend:-s*.05}}}
export function leafMove(now:number,phase=0):EnemyPose{const c=(now*1.9+phase)%1,j=Math.abs(Math.sin(c*Math.PI))* .065;return{scaleX:1-j*.12,scaleY:1+j*.18,scaleZ:1-j*.05,jump:j,wobbleZ:Math.sin(c*Math.PI*2)*.04,travel:0,releaseProgress:-1,secondary:{primaryBend:-j*2.2,secondaryBend:-j*1.2}}}
export function leafSlap(u:number):EnemyPose{const t=clampEnemy01(u),ant=t<.25?Math.sin(t/.25*Math.PI):0,rel=t>=.25&&t<.56?Math.sin((t-.25)/.31*Math.PI/2):t>=.56?1-clampEnemy01((t-.56)/.44):0;return{scaleX:1+ant*.07,scaleY:1-ant*.10,scaleZ:1+ant*.04,jump:Math.sin(t*Math.PI)*.055,wobbleZ:0,travel:rel,releaseProgress:t>=.25?(t-.25)/.75:-1,secondary:{primaryBend:-ant*.68+rel*1.02}}}
export function leafWhirl(u:number):EnemyPose{const t=clampEnemy01(u),ant=t<.30?Math.sin(t/.30*Math.PI/2):0,spin=t>=.30&&t<.58?Math.sin((t-.30)/.28*Math.PI):0,recover=t>=.58?1-clampEnemy01((t-.58)/.42):0;return{scaleX:1+ant*.05,scaleY:1-ant*.08,scaleZ:1+ant*.04,jump:spin*.05,wobbleZ:spin*.08,travel:spin*.12,releaseProgress:t>=.30?(t-.30)/.70:-1,secondary:{primaryBend:-ant*.25,secondaryBend:ant*.2,twist:spin*1.15+recover*.18}}}
function gustMesh(){const g=new THREE.Group();g.name='LeafGustProjectile';const m=new THREE.MeshBasicMaterial({color:'#c8f0a5',transparent:true,opacity:.7,side:THREE.DoubleSide,depthWrite:false});const arc=new THREE.Mesh(new THREE.TorusGeometry(.055,.012,8,20,Math.PI*1.25),m);arc.rotation.x=Math.PI/2;g.add(arc);return g}
const profiles:Record<LeafBehaviorId,EnemyMotionProfile>={
 'leaf-hop-slap':{familyId:'leaf',idle:leafIdle,move:leafMove,attack:leafSlap,hit,defeat,moveDuration:1.35,moveDistance:.78,attackDuration:.58,attackTravelDistance:.36,contactU:.56,defeatDuration:.92},
 'leaf-whirl':{familyId:'leaf',idle:leafIdle,move:leafMove,attack:leafWhirl,hit,defeat,moveDuration:1.25,moveDistance:.88,attackDuration:.72,attackTravelDistance:.12,contactU:.48,defeatDuration:.92,projectile:{kind:'gust',flightSeconds:.32,createMesh:gustMesh,arcHeight:(u)=>Math.sin(clampEnemy01(u)*Math.PI)*.08}}
};
export const getLeafMotionProfile=(id:LeafBehaviorId)=>profiles[id];
